name: data_check_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pip=23.3.1
  - mlflow=2.8.1
  - pandas=1.5.3 # <--- IMPORTANT: Downgrade pandas to a known stable version
  - scikit-learn=1.3.0
  - libstdcxx-ng # <--- Keep this, but without a specific version
  - pip:
    - wandb==0.16.0
    - ydata-profiling==4.12.1
    - pytest==7.2.1
    - pytest-html==3.2.0
    - pytest-cov==4.0.0
    - scipy==1.11.3
    - fsspec==2023.1.0
    - s3fs==2023.1.0