name: data_check_env # Ensure this name is consistent, it was data_check_env in previous instructions
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0 # Keeping this version
  - pip=23.3.1 # Keeping this version
  - mlflow=2.8.1 # Keeping this version
  - pandas=2.1.3 # Keeping this version
  - scikit-learn=1.3.0 # Ensure this is present and correct
  - libstdcxx-ng=11.2.0 # Pin a specific version of libstdcxx-ng
  - gcc-ng=11.2.0      # Add gcc-ng
  - gxx-ng=11.2.0      # Add gxx-ng
  - pip:
    - wandb==0.16.0
    - ydata-profiling==4.12.1
    - pytest==7.2.1
    - pytest-html==3.2.0
    - pytest-cov==4.0.0
    - scipy==1.11.3 # Pin scipy to a specific version
    - fsspec==2023.1.0
    - s3fs==2023.1.0