name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15 # Keep this for your main dev environment
  - mlflow=2.8.1
  - pandas=1.5.3 # Pin pandas to this version for overall compatibility
  - pip=23.0.1
  - gxx_linux-64
  - pip:
    - wandb==0.16.0
    - ydata-profiling==4.12.1
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - ipykernel==6.26.0
    - jupyterlab==4.0.9
    - matplotlib
    - scikit-learn==1.1.3
    - seaborn
    - databricks-cli
    - scipy==1.9.3