name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15 # Keep this for your main dev environment
  - mlflow=2.8.1
  - pandas=1.5.3 # Pin pandas to this version for overall compatibility
  - scikit-learn=1.1.3 # Pin scikit-learn to a version compatible with older scipy/libstdc++
  - scipy=1.9.3 # Pin scipy to a version compatible with older libstdc++
  - pip=23.0.1
  - pip:
    - wandb==0.16.0
    - ydata-profiling==4.12.1
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - ipykernel==6.26.0
    - jupyterlab==4.0.9
    - matplotlib==3.8.2
    - seaborn==0.13.1
    - databricks-cli